/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioPersonasRouteImport } from './routes/studio.personas'
import { Route as StudioContentRouteImport } from './routes/studio.content'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalAiDisclosureRouteImport } from './routes/legal.ai-disclosure'
import { Route as CreatorsHandleRouteImport } from './routes/creators.$handle'
import { Route as ChatHandlePersonaRouteImport } from './routes/chat.$handle.$persona'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioPersonasRoute = StudioPersonasRouteImport.update({
  id: '/studio/personas',
  path: '/studio/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioContentRoute = StudioContentRouteImport.update({
  id: '/studio/content',
  path: '/studio/content',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAiDisclosureRoute = LegalAiDisclosureRouteImport.update({
  id: '/legal/ai-disclosure',
  path: '/legal/ai-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsHandleRoute = CreatorsHandleRouteImport.update({
  id: '/creators/$handle',
  path: '/creators/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatHandlePersonaRoute = ChatHandlePersonaRouteImport.update({
  id: '/chat/$handle/$persona',
  path: '/chat/$handle/$persona',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/agency': typeof AgencyRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/onboarding': typeof OnboardingRoute
  '/creators/$handle': typeof CreatorsHandleRoute
  '/legal/ai-disclosure': typeof LegalAiDisclosureRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/studio/content': typeof StudioContentRoute
  '/studio/personas': typeof StudioPersonasRoute
  '/studio/': typeof StudioIndexRoute
  '/chat/$handle/$persona': typeof ChatHandlePersonaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/agency': typeof AgencyRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/onboarding': typeof OnboardingRoute
  '/creators/$handle': typeof CreatorsHandleRoute
  '/legal/ai-disclosure': typeof LegalAiDisclosureRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/studio/content': typeof StudioContentRoute
  '/studio/personas': typeof StudioPersonasRoute
  '/studio': typeof StudioIndexRoute
  '/chat/$handle/$persona': typeof ChatHandlePersonaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/agency': typeof AgencyRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/onboarding': typeof OnboardingRoute
  '/creators/$handle': typeof CreatorsHandleRoute
  '/legal/ai-disclosure': typeof LegalAiDisclosureRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/studio/content': typeof StudioContentRoute
  '/studio/personas': typeof StudioPersonasRoute
  '/studio/': typeof StudioIndexRoute
  '/chat/$handle/$persona': typeof ChatHandlePersonaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/agency'
    | '/app'
    | '/auth'
    | '/discover'
    | '/onboarding'
    | '/creators/$handle'
    | '/legal/ai-disclosure'
    | '/legal/privacy'
    | '/legal/terms'
    | '/studio/content'
    | '/studio/personas'
    | '/studio/'
    | '/chat/$handle/$persona'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/agency'
    | '/app'
    | '/auth'
    | '/discover'
    | '/onboarding'
    | '/creators/$handle'
    | '/legal/ai-disclosure'
    | '/legal/privacy'
    | '/legal/terms'
    | '/studio/content'
    | '/studio/personas'
    | '/studio'
    | '/chat/$handle/$persona'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/agency'
    | '/app'
    | '/auth'
    | '/discover'
    | '/onboarding'
    | '/creators/$handle'
    | '/legal/ai-disclosure'
    | '/legal/privacy'
    | '/legal/terms'
    | '/studio/content'
    | '/studio/personas'
    | '/studio/'
    | '/chat/$handle/$persona'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AgencyRoute: typeof AgencyRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  DiscoverRoute: typeof DiscoverRoute
  OnboardingRoute: typeof OnboardingRoute
  CreatorsHandleRoute: typeof CreatorsHandleRoute
  LegalAiDisclosureRoute: typeof LegalAiDisclosureRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  StudioContentRoute: typeof StudioContentRoute
  StudioPersonasRoute: typeof StudioPersonasRoute
  StudioIndexRoute: typeof StudioIndexRoute
  ChatHandlePersonaRoute: typeof ChatHandlePersonaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/personas': {
      id: '/studio/personas'
      path: '/studio/personas'
      fullPath: '/studio/personas'
      preLoaderRoute: typeof StudioPersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/content': {
      id: '/studio/content'
      path: '/studio/content'
      fullPath: '/studio/content'
      preLoaderRoute: typeof StudioContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/ai-disclosure': {
      id: '/legal/ai-disclosure'
      path: '/legal/ai-disclosure'
      fullPath: '/legal/ai-disclosure'
      preLoaderRoute: typeof LegalAiDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/$handle': {
      id: '/creators/$handle'
      path: '/creators/$handle'
      fullPath: '/creators/$handle'
      preLoaderRoute: typeof CreatorsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$handle/$persona': {
      id: '/chat/$handle/$persona'
      path: '/chat/$handle/$persona'
      fullPath: '/chat/$handle/$persona'
      preLoaderRoute: typeof ChatHandlePersonaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AgencyRoute: AgencyRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  DiscoverRoute: DiscoverRoute,
  OnboardingRoute: OnboardingRoute,
  CreatorsHandleRoute: CreatorsHandleRoute,
  LegalAiDisclosureRoute: LegalAiDisclosureRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  StudioContentRoute: StudioContentRoute,
  StudioPersonasRoute: StudioPersonasRoute,
  StudioIndexRoute: StudioIndexRoute,
  ChatHandlePersonaRoute: ChatHandlePersonaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
